app = "ryuwebsocket"
primary_region = "gru"  

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/builder:22"
  buildpacks = ["heroku/nodejs"]
  [build.args]
    NODE_ENV = "production"

[env]
  PORT = "3000"  
  NODE_ENV = "production"
  APP_URL = "https://api.ryuzaki.cloud"
  NO_CACHE = "true"  

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true

  
  [http_service.http_options]
    compress = true
    [http_service.http_options.response_headers]
      "X-WebSocket-Enabled" = "true"
      "Connection" = "Upgrade"
      "Upgrade" = "websocket"

  
  [[http_service.http_options.headers]]
    for = "/profile/*"
    [http_service.http_options.headers.set]
      "Cache-Control" = "no-cache, no-store, must-revalidate"
      "Pragma" = "no-cache"
      "Expires" = "0"
      "CDN-Cache-Control" = "no-cache"
      "Vary" = "*"

  
  [[http_service.http_options.headers]]
    for = "/ws"  
    [http_service.http_options.headers.set]
      "Sec-WebSocket-Protocol" = "chat"
      "Cache-Control" = "no-store"

[services]
  protocol = "tcp"
  processes = ["app"]

  [services.concurrency]
    hard_limit = 100  
    soft_limit = 80

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 3


[deploy]
  strategy = "rolling"
  max_unavailable = 0